#!/usr/bin/env bash
# Interactive setup: gets Telegram chat ID and Vast.ai API key,
# saves to /etc/gpu_monitor.conf, restarts the service.

set -euo pipefail

TELEGRAM_TOKEN="8930785275:AAGFwVssjqAe5EW0e3quosU4u_D9M0XXrCo"
CONFIG_FILE="/etc/gpu_monitor.conf"

echo "========================================="
echo "  GPU Monitor Setup"
echo "========================================="

# ── Step 1: get Telegram chat ID ─────────────
echo ""
echo "[1/2] Telegram Setup"
echo "  Open Telegram and send any message to @ronyzap_bot now."
echo "  Press ENTER when done..."
read -r

echo "  Looking up your chat ID..."
RESPONSE=$(curl -sf "https://api.telegram.org/bot${TELEGRAM_TOKEN}/getUpdates" 2>/dev/null) || {
    echo "  ERROR: Could not reach Telegram API. Check internet connection."
    exit 1
}

CHAT_ID=$(echo "$RESPONSE" | python3 -c "
import sys, json
data = json.load(sys.stdin)
results = data.get('result', [])
if not results:
    print('')
else:
    last = results[-1]
    msg = last.get('message') or last.get('channel_post') or {}
    chat = msg.get('chat', {})
    print(chat.get('id', ''))
" 2>/dev/null)

if [[ -z "$CHAT_ID" ]]; then
    echo ""
    echo "  Could not auto-detect chat ID."
    echo "  Please send a message to @ronyzap_bot, then enter your chat ID manually."
    echo "  (Find it at: https://api.telegram.org/bot${TELEGRAM_TOKEN}/getUpdates)"
    read -rp "  Enter chat ID: " CHAT_ID
fi

echo "  Chat ID: $CHAT_ID"

# Test send
echo "  Sending test message..."
curl -sf -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
    -d chat_id="$CHAT_ID" \
    -d parse_mode="HTML" \
    -d text="✅ <b>GPU Monitor connected!</b> — $(hostname)
Setup complete. You'll receive alerts here." > /dev/null && \
    echo "  Test message sent! Check Telegram." || \
    echo "  WARNING: Test message failed. Check token and chat ID."

# ── Step 2: Vast.ai API key ──────────────────
echo ""
echo "[2/2] Vast.ai Setup"
read -rp "  Enter your Vast.ai API key (or press ENTER to skip): " VASTAI_KEY

# ── Save config ──────────────────────────────
echo ""
echo "  Saving config to $CONFIG_FILE..."
cat > "$CONFIG_FILE" <<EOF
# GPU Monitor configuration — generated by setup.sh $(date)
TELEGRAM_CHAT_ID="$CHAT_ID"
VASTAI_API_KEY="$VASTAI_KEY"
EOF
chmod 600 "$CONFIG_FILE"

echo "  Config saved."

# ── Restart service ──────────────────────────
if systemctl is-active --quiet gpu-monitor 2>/dev/null; then
    echo "  Restarting gpu-monitor service..."
    systemctl restart gpu-monitor
    echo "  Service restarted."
else
    echo "  (gpu-monitor service not running — run: sudo bash install.sh)"
fi

echo ""
echo "========================================="
echo "  Setup complete!"
echo "  Logs: tail -f /var/log/gpu_monitor.log"
echo "========================================="
